version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - ./backend:/app
      - /app/bin
      - /app/obj
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CORS_ALLOWED_ORIGINS=http://localhost:5173
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8080/todos']
      interval: 5s
      timeout: 3s
      retries: 5

  frontend:
    depends_on:
      backend:
        condition: service_healthy
    build:
      context: ./frontend
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8080
    command: pnpm dev --host
